### ISSUE TITLE
Release 1.8.0 - PHP Fatal error: Using $this when not in object context in [file path]

### ISSUE THREAD

**Issue by a3rev** [a3rev/a3-lazy-load#1]
@alextuan Reports of a a Fatal Error in release 1.8.0
PHP Fatal error: Using $this when not in object context in [file path]/plugins/a3-lazy-load/classes/class-a3-lazy-load.php on line 279

Happens while loading any page with lazy loaded elements.

Reported [here](https://wordpress.org/support/topic/update-causes-fatal-error/), [here](https://wordpress.org/support/topic/latest-post-generates-error-on-homepage/) and [here](https://wordpress.org/support/topic/how-to-skip-images-classes/#post-9180062)

**Comment by alextuan** [comment]
Solved
