### ISSUE TITLE
Feature Request: Lazy Load background images

### ISSUE THREAD

**Issue by jmrieger** [a3rev/a3-lazy-load#11]
http://ressio.github.io/lazy-load-xt/demo/bg.htm

Lazy Load XT already has a plugin for it. This feature would be amazing!

**Comment by ondoheer** [comment]
Maybe a simple redme comment would be the way to begin? It would then just need to be added to the admin panel as an option and instructions on how to add the data-bg attribute to the required tag

**Comment by a3rev** [comment]
@jmrieger @ondoheer 

The Lazy Load TX script http://ressio.github.io/lazy-load-xt/demo/bg.htm only supports themes that load the background image like this

`<p data-bg=“http://lorempixel.com/300/200/business/10” ></p>`

If it is and we where to add support for that via the background loading plugin - then that would work.

The reality is however that the vast majority of themes - most of them i believe, the background images are not added by html tag, for example <img> they are added by style

Not only are they added by style but can be added from style.css or inline style <style>  or direct on html tags with attribute is style=“”

for example with <div class=“header”></div> , can set background image for it with 1 in 3 way
from style.css
`.header{
background-image: url( image_url ); // or background: url( image_url );
}`

OR inline style

`<style>
.header{
background-image: url( image_url ); // or background: url( image_url );
}
</style>`

OR direct on that <div>

`<div class=“header” style=“background-image: url( image_url );“></div>`
or
`<div class=“header” style=“background: url( image_url ) no-repeat top left;“></div>`

Theme developers would have to refactor their themes background image loading from any of those to just use

`<p data-bg=“http://lorempixel.com/300/200/business/10” ></p>`

A developer with a custom theme might do that but a parent theme developer would be highly unlikely to ever do that to just enable background image lazy load. I know we would not do it with our responsi Theme Framework.
