### ISSUE TITLE
Issues with single / double quoted tags

### ISSUE THREAD

**Issue by stayallive** [a3rev/a3-lazy-load#12]
I created an [support ticket](https://wordpress.org/support/topic/cannot-exclude-avatar-image-from-being-lazy-loaded-using-class/) on WordPress.org before realising the plugin is open source :)

Original message:
> I am using the following code to insert an avatar on my page, however this generates an output that fails to exclude this specific avatar from being lazy loaded.
>
> ```
> <?php echo get_avatar( get_the_author_meta( 'ID' ), 128, '', '', [ 'class' => 'no-lazy' ] ); ?>
> ```
>
> This generates an `<img>` tag which uses `'` instead of `"` (so `class='no-lazy'` instead of `class="no-lazy"`), the regex is not taking that in account thus not excluding this image from being lazy loaded.

After digging furthur I noticed more regexes dealing with HTML tags are expecting only `"` while a `'` can also be used instead thus rendering some of the code not working for tags that use a single quote, changing all the instances for `[\'"]` should do the trick I think. 

If time permits it I will create a PR myself, but if someone else want to take a stab at it I wouldn't object ofcourse 👍

**Comment by a3rev** [comment]
@stayallive 

Hi Alex - you probably saw that i replied on the WordPress forum and marked the ticket as resolved. Hoping you will find the time to do this and send a PR

**Comment by a3rev** [comment]
@stayallive Hi Alex - have you made any progress on a PR for this issue?

**Comment by a3rev** [comment]
Resolved in [release v 2.0.0](https://github.com/a3rev/a3-lazy-load/releases/tag/2.0.0)

**Comment by stayallive** [comment]
Very nice thanks @a3rev & @joneslloyd for the effort, I see I totally ghosted this issue after reporting 😟

Thank you both for following up and fixing it!

**Comment by joneslloyd** [comment]
Don't worry about it :)
