### ISSUE TITLE
Add Compatibility with Adavanced Custom Fields

### ISSUE THREAD

**Issue by a3rev** [a3rev/a3-lazy-load#14]
Request for full compatibility with ACF plugin https://wordpress.org/plugins/advanced-custom-fields/ and Premium version features https://www.advancedcustomfields.com/pro/

Posted on wp forum here https://wordpress.org/support/topic/acf-support-8/ from @ondoheer

**Comment by a3rev** [comment]
[PR submitted](https://github.com/a3rev/a3-lazy-load/pull/15)

**Comment by alextuan** [comment]
It's merged https://github.com/a3rev/a3-lazy-load/commit/e0a5e64bcbe84dcb014203fcec1647b0454e22c1

**Comment by mnenchev** [comment]
Iis this code change published in the WP plugins place?
