### ISSUE TITLE
WordPress Tool Bar User Avatar conflict

### ISSUE THREAD

**Issue by a3rev** [a3rev/a3-lazy-load#2]
When a3 Lazy Load is activated users no longer see their avatar picture when hovering over the toolbar in the top right corner of the page. The menu drops down, but there is just a black space where the avatar should be.  [From support forum ](https://wordpress.org/support/topic/user-avatar-in-toolbar/)

Bug Verified - only affect user Avatar on front end - still shows on admin 

http://screencast-o-matic.com/watch/cb1VjgXHt5

@alextuan

**Comment by alextuan** [comment]
Just resolved that confliction

[Commit here](https://github.com/a3rev/a3-lazy-load/commit/bdd94243ef2d320634281ab536b7d58768c55ebc)
