### ISSUE TITLE
Which is the proper way to desactivate lazy load in some pages?

### ISSUE THREAD

**Issue by rafaelfigueiredo-l** [a3rev/a3-lazy-load#25]
First of all thanks for your plugin. It does a hell of a job. Congrats!

I'm using ninja forms and it's crashing when using lazy loader together and I know how to detect if I'm in ninja forms page. Then I want to pass this information to your plugin and desactivate it in those pages.

Thanks again!

**Comment by rafael-figueiredogluz** [comment]
I achieve what I want removing the action bellow:

remove_action('wp', 'a3_lazy_load_instance', 10, 0);

And create a new action to replace with my if statement.

There is a better way? Thanks!
