### ISSUE TITLE
doesent not work on Firefox 64

### ISSUE THREAD

**Issue by cultd3ad** [a3rev/a3-lazy-load#27]
Hello,

this script doesent Work on Firefox 64 with DIVI Theme and Builder (newest Version and WP) , only the placeholder.gif is still available.
On Google Chrome will it works... Can anybody confirm this, I do not get it!

thanks in advance
M

**Comment by a3rev** [comment]
You need to c;lear your Firefox browser cache - but I think you would have worked that out by now.

**Comment by pklopping** [comment]
I'm experiencing a similar issue with Firefox Quantum 66.0.2 (64-bit)

It's happening with a fresh install, so the browser cache can't be an issue.

**Comment by a3rev** [comment]
Not duplicatable and closed

**Comment by Vegekku** [comment]
Hey everyone! This is still happening on Firefox. Chrome run perfectly.

> Not duplicatable and closed
