### ISSUE TITLE
Picture elements are not supported

### ISSUE THREAD

**Issue by tsteur** [a3rev/a3-lazy-load#29]
Is it possible to apply this PR https://github.com/ressio/lazy-load-xt/pull/116/files ? Using this plugin with `webp` images won't work otherwise but both webp images and lazy loading is recommended by Google Page Speed.

**Comment by tsteur** [comment]
Actually, it seems like an extra file will need to be embedded to make this work: `jquery.lazyloadxt.picture.js`

**Comment by a3rev** [comment]
@tsteur 

Just [released v 2.1.0 ](https://github.com/a3rev/a3-lazy-load/releases/tag/2.1.0) which includes full and automatic support for WebP images.
