### ISSUE TITLE
Change "Proton" to "Photon"

### ISSUE THREAD

**Issue by nabtron** [a3rev/a3-lazy-load#37]
It's supposed to say Jetpack pHoton, not pRoton.

You're welcome.

**Comment by a3rev** [comment]
@nabtron 

Thanks - will fix that typo on the next update.

**Comment by a3rev** [comment]
@nabtron 

Typo fixed in [release 2.3.2 ](https://github.com/a3rev/a3-lazy-load/releases/tag/2.3.2)

Thanks
