### ISSUE TITLE
JS parameters rendered twice (minor)

### ISSUE THREAD

**Issue by galbaras** [a3rev/a3-lazy-load#4]
For some reason, the following double declarations are inserted into the page:

`<script type="text/javascript">`
`/* <![CDATA[ */`
`var a3_lazyload_params = {"apply_images":"1","apply_videos":"1"};`
`var a3_lazyload_params = {"apply_images":"1","apply_videos":"1"};`
`/* ]]> */`
`</script><script type="text/javascript" src="//www.ronitbaras.com/wp-content/plugins/a3-lazy-load/assets/js/jquery.lazyloadxt.min.js?ver=1.8.2" defer></script><script type="text/javascript" src="//www.ronitbaras.com/wp-content/plugins/a3-lazy-load/assets/js/jquery.lazyloadxt.srcset.min.js?ver=1.8.2" defer></script><script type="text/javascript">`
`/* <![CDATA[ */`
`var a3_lazyload_extend_params = {"edgeY":"600"};`
`var a3_lazyload_extend_params = {"edgeY":"600"};`
`/* ]]> */`
`</script><script type="text/javascript" src="//www.ronitbaras.com/wp-content/plugins/a3-lazy-load/assets/js/jquery.lazyloadxt.extend.js?ver=1.8.2" defer></script>`

**Comment by alextuan** [comment]
@galbaras thanks for report that issue, we will fix it on next version

**Comment by a3rev** [comment]
Released in Maintenance [Version 1.8.5](https://github.com/a3rev/a3-lazy-load/releases/tag/1.8.5) 

From Changelog
Tweak - Remove duplicate parameters from plugin scripts. Thanks to @galbaras for reporting the issue
