### ISSUE TITLE
Lazy loading images programmatically

### ISSUE THREAD

**Issue by galbaras** [a3rev/a3-lazy-load#5]
I have images embedded by PHP code in the theme. Is there a public function or filter I can use to make them lazy load?

Is there a developer guide for this plugin somewhere?

**Comment by alextuan** [comment]
@galbaras you can call apply_filters for 'a3_lazy_load_html' tag from your PHP code in the theme so that our plugin can filter and apply Lazy Load to your content

For example:

```
$include_noscript = true; // true|false
$your_html = apply_filters( 'a3_lazy_load_html', $your_html, $include_noscript );
```

**Comment by petermyo** [comment]
Hi alextuan

Can we use this apply filter in the iframe?

**Comment by alextuan** [comment]
@petermyo yes, you can use that to apply for iframe, it apply for images, videos, iframes
